
import ENV from './url';
import config from './index'
const CONSTANTS = {
  API_BASE_URL: ENV[config.PROJECT_ENV].INT,
  AUTH_BASE_URL: ENV[config.PROJECT_ENV].AUTH,
  PROCUREMENT_BASE_URL: ENV[config.PROJECT_ENV].PROCUREMENT,
  ADDRESS_BASE_URL: ENV[config.PROJECT_ENV].ADDRESS,
  MONITORING_BASE_URL: ENV[config.PROJECT_ENV].MONITORING,
  SAP_BASE_URL: ENV[config.PROJECT_ENV].SAP,
  URL_BASE_URL: ENV[config.PROJECT_ENV].URL,
  API_URL: {
    DEACTIVATE_USER: '/login/user/updateStatus',
    QR_DETAIL: '/feedback/getQRData/',
    QR_BATCH_DETAIL: '/feedback/getQRDataByBatch/',
    BAR_DETAIL: '/feedback/getBarCodeData/',
    SUB_LIST: '/feedback/subCategory/',
    GET_TOKEN: '/login/auth/getTokenDetails',
    LOGIN: '/login/auth/login',
    SIGNUP: '/login/customer/signUP',
    GETUSER_DATA: '/login/user/getData',
    SESSION_ID: '/login/user/getSession',
    BRANCH_ACCESS: '/login/user/getBranchAccess',
    SUBMIT_FEEDBACK: '/feedback/saveFeedback',
    FEEDBACK_LIST: '/feedback/listing',
    LOGOUT: '/login/auth/logout',
    FORGETPASSWORD: '/login/auth/forgotPassword',
    SEND_OTP: '/login/customer/sendOtp',
    PRODUCTVARIANTS: '/productVariant/getAllProductVariants',
    ISGSTINEXIST: '/login/customer/isGstInExist',
    UPDATE_DETAILS: '/login/user/updateDetails',
    RESET_PASSWORD: '/login/auth/resetPassword',
    PROCUREMENT_UPLOAD: '/procurement/upload',
    SAVE_BUSINESS_DETAILS: '/login/customer/saveBusinessDetails',
    VALIDATE_PINCODE: '/login/customer/validatePinDetails/',
    BANK_DETAILS: '/login/customer/saveMultipleBankDetails',
    SAVE_DOCUMENTS: '/login/customer/saveDocuments',
    SAVE_MULTIPLE_ADDRESS: '/login/customer/saveMultipleAddresses',
    DELETE_BANKDETAILS: '/login/customer/deleteBankDetails',
    RFCSUBMIT: '/login/customer/rfcSubmit/',
    GET_CREDIT_BALANCE: '/login/customer/getCreditBalance',
    GET_SESSION: '/login/user/getSession',
    SEARCH_PLANTSBYCOMPANY: `/login/branch/searchPlantsByCompany/`,
    SEARCH_PLANTS: '/login/branch/searchPlants/',
    DISPATCH_SEARCH_DETAILS: '/procurement/asn/es/search',
    SHIPMENT_TIMESTAMP: '/latestUpdation/getShipmentTimeStamp/',
    REFRESH_DATA: '/rest/invoice/refreshData',
    BRANCH_ACCESS: '/login/user/getBranchAccess',
    REGION_BY_PLANTS: '/scheduledelivery/regionByPlants',
    CUSTOMER_LIST: '/asn/customerList',
    EXPORT_DATA: '/feedback/exportShipment/',
    ISFILE_EXISTS: '/login/auth/isFileExist',
    SAP_REPORT: '/api/invoice/exportInvoicesFromSap',
    GET_LCBG_BALANCE: '/po/payments/getLCBGBalance',
    DRAFT_MOUZINCLIST: '/po/mou/getallStatus/DraftMOUZinc',
    MOU_LIST: '/po/mou/mouList',
    ZINC_LIST: '/mou/zinc/nfa/list',
    ZINC_DRAFTMOU: '/mou/zinc/listDraft',
    EXPORT_ZINCDRAFT: '/mou/zinc/exportDraft',
    EXPORT_ZINCMOU: '/mou/zinc/exportMou',
    EXPORTNFA:'/nfa/exportNFA',
    GET_MOUSTATUS: '/po/mou/getallStatus/MOU',
    APPROVED_CUSTOMERLIST: '/login/customer/approvedCustomerList',
    GET_APPROVERTYPE: '/login/user/getApproverType/19039/1/1',
    FETCH_MOUAPPROVER_EMAILNAME: '/login/user/fetchMOUApproverEmailIdNameList',
    FETCH_CREATORNAME: '/po/mou/fetchCreatorName',
    SAVE_TOKEN: '/login/notifications/saveDeviceToken',
    REMOVE_TOKEN: '/login/notifications/logoutDeviceToken',
    NFALISTING: '/nfa/NFAListing',
    EXPORT_CONTRACTLIST: '/po/mou/exportContractList',
    MOU_CUSTOMER_LIST: '/login/customer/customerList',
    NFA_APPROVER_USERID_NAMELIST: '/login/user/fetchNFAApproverUserIdNameList',
    GET_NFA: `/nfa/getNFA`,
    DOWNLOAD_NFA_PDF: '/nfa/downloadDOPdf/',
    DRAFT_MOU: `/po/mou/getallStatus/DraftMOU`,
    FETCH_DRAFTMOU: '/po/mou/fetchDraftMou',
    CART_COUNT: '/v1/procurement/cart/user/',
    EXPORT_DRAFTCONTRACT_MOU: '/po/mou/exportDraftContractList',
    ADMIN_LISTING: '/feedback/adminListing',
    GET_COMPLAINT: '/feedback/getComplaint',
    GET_SHIPMENT: '/po/mou/getShipFrom/',
    GET_ALL_CCHPPRODUCTVARIANTS: '/productVariant/getAllCCHPProductVariants',
    FEEDBACK_CATEGORY: '/feedback/category/',
    FEEDBACK_SUBCATEGORY: '/feedback/subCategory',
    GET_USERBYROLE: '/login/customer/getUserByRole/',
    COMPLAINTS_MAIL: '/feedback/complaintMails/',
    UPDATE_FEEDBACK: '/feedback/updatefeedback/',
    GETNOTIFICATION: '/login/notifications/getNotifications/',
    GETUNREADCOUNT: '/login/notifications/getUnreadCount/',
    MARKASREAD: '/login/notifications/markAsRead/',
    DELETENOTI: '/login/notifications/delete/',
    CUSTOMERLISTING: '/login/customer/customerListing',
    PLANTREQUEST: '/login/plant/plantRequests',
    GETALLBYCOMPANY: '/login/branch/getAllByCompany',
    GETBYCOMPANY: '/login/user/getByCompany',
    USER_GET: '/login/user/get',
    COMPANY_GET: '/login/company/get',
    GETDETAILS: '/login/branch/getDetails',
    APPROVEACTION: '/login/customer/approverAction',
    UPDATE_CUSTOMERUSER: '/login/user/updateCustomerUser',
    REJECTACTION: '/login/customer/rejectAction',
    PENDING_TASKS: '/supplierDashboard/pendingTask',
  },
  PDF_URL: {
    AUTH_URL_COPPER_INVOICEPDF_UAT: `https://vedanta-sapqa.moglilabs.com/vedanta-sftp/`,
    AUTH_URL_COPPER_INVOICEPDF_PROD: `https://vedanta-auth.moglix.com/vedanta/Copper/Invoice/`,
    AUTH_URL_COPPER_LRPDF_UAT: `https://vedanta-sapqa.moglilabs.com/vedanta-sftp/`,
    AUTH_URL_COPPER_LRPDF_PROD: `https://vedanta-auth.moglix.com/vedanta/Copper/LR/`,
    AUTH_URL_COPPER_PLPDF_UAT: `https://vedanta-sapqa.moglilabs.com/vedanta-sftp/`,
    AUTH_URL_COPPER_PLPDF_PROD: `https://vedanta-auth.moglix.com/vedanta/Copper/Packaging_List/`,
    AUTH_URL_COPPER_TCPDF_UAT: `https://vedanta-sapqa.moglilabs.com/vedanta-sftp/`,
    AUTH_URL_COPPER_TCPDF_PROD: `https://vedanta-auth.moglix.com/vedanta/Copper/Test_Certificate/`,

    AUTH_URL_HZL_INVOICEPDF_PROD: "https://vedanta-auth.moglix.com/vedanta/HZL/Invoice/",
    AUTH_URL_HZL_TCPDF_PROD: "https://vedanta-auth.moglix.com/vedanta/HZL/Test_Certificate/",
    AUTH_URL_HZL_LRPDF_PROD: "https://vedanta-auth.moglix.com/vedanta/HZL/LR/",
    AUTH_URL_HZL_PLPDF_PROD: "https://vedanta-auth.moglix.com/vedanta/HZL/Packing_List/",
    AUTH_URL_HZL_INVOICEPDF_UAT: "https://vedanta-sapqa.moglilabs.com/vedanta-sftp/HZL/",
    AUTH_URL_HZL_TCPDF_UAT: "https://vedanta-sapqa.moglilabs.com/vedanta-sftp/HZL/",
    AUTH_URL_HZL_LRPDF_UAT: "https://vedanta-sapqa.moglilabs.com/vedanta-sftp/HZL/",
    AUTH_URL_HZL_PLPDF_UAT: "https://vedanta-sapqa.moglilabs.com/vedanta-sftp/HZL/",

    AUTH_URL_ALUMINIUM_INVOICEPDF_PROD: "https://vedanta-auth.moglix.com/vedanta-data/",
    AUTH_URL_ALUMINIUM_PLPDF_PROD: "https://vedanta-auth.moglix.com/Uploads/PackingList/",
    AUTH_URL_ALUMINIUM_LRPDF_PROD: "https://vedanta-auth.moglix.com/vedanta-data/",
    AUTH_URL_ALUMINIUM_TCPDF_PROD: "https://vedanta-auth.moglix.com/vedanta-data/",
    AUTH_URL_ALUMINIUM_INVOICEPDF_UAT: 'https://vedanta-authqa.moglilabs.com/vedanta-data/',
    AUTH_URL_ALUMINIUM_PLPDF_UAT: "https://vedanta-auth.moglix.com/Uploads/PackingList/",
    AUTH_URL_ALUMINIUM_LRPDF_UAT: "https://vedanta-auth.moglix.com/vedanta-data/",
    AUTH_URL_ALUMINIUM_TCPDF_UAT: "https://vedanta-authqa.moglilabs.com/vedanta-data/",

    // AUTH_URL_ALUMINIUM_CREDITDEBITPDF: '/Uploads/CreditDebit/00',
    // AUTH_URL_ALUMINIUM_INVOICEPDF: '/vedanta-data/',
    // AUTH_URL_COPPER_INVOICEPDF: '/vedanta-sftp/',
    // AUTH_URL_COPPER_PLPDF: '/vedanta-sftp/',
    // AUTH_URL_HZL_INVOICEPDF: '/vedanta-sftp/HZL/',
    // AUTH_URL_COPPER_CREDITPDF: '/vedanta-sftp/',
    // AUTH_URL_COPPER_DEBITPDF: '/vedanta-sftp/',
    // AUTH_URL_HZL_TCPDF: '/vedanta-sftp/HZL/',
    // AUTH_URL_COPPER_TCPDF: '/vedanta-sftp/',
    // AUTH_URL_ALUMINIUM_PLPDF: '/Uploads/PackingList/',
    // AUTH_URL_HZL_PLPDF: '/vedanta-sftp/HZL/',
    // AUTH_URL_HZL_LRPDF: '/vedanta-sftp/HZL/',
    // AUTH_URL_CU_LRPDF: '/vedanta-sftp/',
    // AUTH_URL_ZINC_MOUPDF: '/vedanta-sftp/HZL/MOU/',
    // AUTH_URL_ALUMINIUM_LRPDF: '/vedanta-data/',

  },
  TOKEN: {
    PROD: 'f3b027e2-46a4-4d8c-9c3b-92812d56fa23-1713264798123',
    UAT: 'f3b027e2-46a4-4d8c-9c3b-92812d56fa23-1713264798123',
    // '0f35d83c-4535-468f-9baa-30be6677b7b7',
  },
  WEBURL: {
    CATEGORY: `${ENV[config.PROJECT_ENV].BROWSER}/?isApp=true`,
    SIGNUP: `${ENV[config.PROJECT_ENV].URL}/#/signup`,
    TAB_WEB: `${ENV[config.PROJECT_ENV].URL}/#/pages/`,
    Learning: `${ENV[config.PROJECT_ENV].URL}/#/pages/learningCenter/customeruserManual`,
    Rate: `${ENV[config.PROJECT_ENV].URL}/#/pages/rating`,
    MOU: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/list/`,
    DRAFTMOUV1: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/draftcreate`,
    DRAFTMOU: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/draftcreateV2`,
    DRAFTMOUZINC: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/createzincdraft`,
    DRAFTMOUCOPPER: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/createcopperdraft`,
    DRAFTMOUCOPPERV2: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/createcopperdraftV2`,
    NFAMOUV1: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/nfa/createNFAV2`,
    NFAMOU: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/nfa/createNFA`,
    CONTRACTLISTMOUV1: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/create`,
    CONTRACTLISTMOU: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/createV2`,
    CONTRACTLISTMOUZINC: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/zicnfa`,
    CONTRACTLISTMOUCOPPER: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/createcoppermou`,
    CONTRACTLISTMOUCOPPERV2: `${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/createmouV2`,
    NFASUPPLIER:`${ENV[config.PROJECT_ENV].URL}/#/pages/vmou/nfa/createNFA`,
    TERMS: `${ENV[config.PROJECT_ENV].URL}/#/terms`,
    NOTIFICATION: `${ENV[config.PROJECT_ENV].URL}/#/pages/mnotification`,
  },
  BU: 'Aluminium',
  TOKEN_RESP: {
    successful: true,
    message: null,
    status: '200',
    errors: null,
    warnings: null,
    data: {
      userId: '18040',
      branchId: '14564',
      companyId: '11105',
      application: '1',
      token: '580416b6-ee5b-499d-8565-906ab8a17ce0',
      customerCode: '11105',
      customerName: 'Darshan Shah',
      code: '0000500587',
      customerPlantName: 'INDU CORPORATION PVT LTD',
      businessUnit: 'Aluminium',
    },
  },
  SAVE_FEEDBACK: {
    code: 200,
    success: true,
    message: 'successfully data saved ',
    data: {
      id: 'CC2203070004',
      code: '0000500587',
      customerPlantName: 'INDU CORPORATION PVT LTD',
      dispatchCompany: 'VALC',
      dispatchCompanyId: '11103',
      productName: 'Ingot',
      productId: 'Ingot',
      quantity: 44,
      feedbackCategory: 'Finance',
      feedbackCategoryId: 1,
      feedbackSubcategory: 'Credit and Debit Notes',
      feedbackSubcategoryId: 2,
      complaintType: 'Feedback',
      complaintTypeId: null,
      invoiceNo: 'F22152106798',
      batchNo: '22A3561401',
      details: 'EC INGOT 99.7% -P1020',
      customerCode: '11103',
      customerName: 'Darshan Shah',
      status: 'Open',
      businessUnit: 'Aluminium',
      ageing: null,
      closingDate: null,
      closingDays: null,
      shipFromId: null,
      shipFrom: null,
      firActionDays: null,
      firDate: null,
      qcirActionDays: null,
      qcirDate: null,
      fcirActionDays: null,
      fcirDate: null,
      supplierStatus: 'FIR Pending',
      regionalManagerId: null,
      productManagerId: null,
      supplierComment: null,
      supplierDocuments: null,
      mailToId: null,
      complaintMail: null,
      firBy: null,
      stage: 0,
      castNo: null,
      preliminaryFindings: null,
      qcirRemark: null,
      investigatedBy: null,
      plantVisit: null,
      qcirBy: null,
      investigationReport: null,
      preventiveAction: null,
      complaintProposalSettelment: null,
      fcirRemark: null,
      complaintQty: null,
      materialRejected: null,
      attendedBy: null,
      plantVisitedOn: null,
      fcirBy: null,
      marketingRemarks: null,
      finalRemark: null,
      closureBy: null,
      createdOn: 1646638044597,
      createdBy: 'Darshan',
      createdById: 18038,
      updatedBy: null,
      updatedOn: null,
      filesPath: [],
    },
  },
};

export default CONSTANTS;
