export const STATE_STATUS = {
    FETCHING: "FETCHING",
    FETCHED: "FETCHED",
    FAILED_FETCH: "FAILED_FETCH",
    UNFETCHED: "UNFETCHED",
    SERVER_ERROR: "SERVER_ERROR",
    UPDATED: "UPDATED",
    UPDATING: "UPDATING",
    NOT_UPDATED: "NOT_UPDATED",
    FAILED_UPDATE: "FAILED_UPDATE",
  };
  